version: '3'

services:
  db:
    image: postgres:13.3-alpine
    restart: unless-stopped
#    ports:
#      - '5432:5432'
#      - '5433:5432'
    volumes:
    - qa-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zero

  ui:
    image: zero-ui
    restart: unless-stopped
    depends_on:
      - api
    ports:
    - 8080:80
    environment:
      API_URL: http://localhost:3333

  studio:
    image: zero-api
    restart: unless-stopped
    depends_on:
      - db
    profiles:
      - debug
    ports:
      - '5555:5555'
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/zero"
    command: prisma studio

  api:
    image: zero-api
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - '3333:3333'
    volumes:
    - qa-backend-temp:/tmp
    - qa-backend-uploaded_files:/uploaded-files
    environment:
      LOG_LEVELS: "log,error,warn,debug,verbose"
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/zero"
      JWT_SECRET: "secret"
      JWT_TTL: "24h"

volumes:
  qa-db-data:
  qa-backend-temp:
  qa-backend-uploaded_files:
