/*
 * Generated by orval v5.4.12 🍺
 * Do not edit manually.
 * Energy Web Zero API
 * OpenAPI spec version: 0.3
 */
export interface LoginDataDTO {
  username: string;
  password: string;
}

export interface LoginResponseDataDto {
  accessToken: string;
}

export type UserRole = 'seller' | 'buyer' | 'admin';


export const UserRole = {
  seller: 'seller' as UserRole,
  buyer: 'buyer' as UserRole,
  admin: 'admin' as UserRole,
};

export interface CreateUserDto {
  email: string;
  firstName: string;
  lastName: string;
  roles: UserRole[];
  password: string;
}

export interface UserEntity {
  id: number;
  email: string;
  firstName: string;
  lastName: string;
  roles: UserRole[];
}

export interface UpdateUserDto {
  firstName?: string;
  lastName?: string;
  roles?: UserRole[];
  password?: string;
}

