name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
      - develop
      - feat/facilities
      - feat/products

jobs:
  cancel-previous:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
  build:
    runs-on: ubuntu-latest
    needs: [cancel-previous]

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_DB: 'zero'
          POSTGRES_PASSWORD: 'postgres'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 10s
          --health-retries 10
        ports:
        - 5432:5432
      mailhog:
        image: mailhog/mailhog
        ports:
          - 1025:1025
          - 8025:8025
    steps:
      - uses: actions/checkout@v2

      - name: Setup app dependencies
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: "./node_modules"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock', '**/schema.prisma') }}

      - name: Install dependencies
        run: yarn install

      - name: Check linting
        run: yarn run lint

#      - name: Audit package dependencies
#        run: yarn audit --level=critical

      - name: Create database schema
        run: yarn db:migrate:ci
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/zero"

      - name: Run backend tests
        run: yarn test:zero-api
        env:
          JWT_SECRET: secret
          EMAIL_CONFIRMATION_TTL: 3600
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/zero"
          SMTP_URL: "smtp://localhost:1025"
          AWS_BUCKET: "ew-zero-uploaded-files-dev"
          AWS_REGION: "us-west-2"
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}

# Disabled until UI tests are fixed
#      - name: Run UI tests
#        run: yarn test:zero

      - name: Build project
        run: yarn build
