name: Lint & test

on:
  pull_request:
    branches:
      - '*'

jobs:
  cancel-previous:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  run-tests:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: 'zero'
          POSTGRES_PASSWORD: 'postgres'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 10s
          --health-retries 10
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    needs: cancel-previous
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14'

    - name: Install application
      run: |
        yarn

    - name: Build application
      run: |
        yarn build

    - name: Run apps tests
      run: |
        yarn affected:test

    - name: Run e2e tests
      run: |
        yarn affected:e2e
